Monkey patching #setup_security_groups for use in vagrant
At least for vagrant this caused: lib/rubber/cloud/base.rb:100:in `setup_security_groups': undefined method `split' for ["master.foo.com", "worker.foo.com"]:Array (NoMethodError).
The :host argument is passed as an array, not as string.